services:
  db:
    image: postgres:15
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../files/postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - odoo-internal

  odoo:
    image: odoo:19.0
    container_name: odoo-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
    environment:
      HOST: db
      PORT: 5432
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../files/odoo-data:/var/lib/odoo
      - ../files/extra-addons:/mnt/extra-addons
    networks:
      - odoo-internal
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo.rule=Host(`${ODOO_DOMAIN}`)
      - traefik.http.routers.odoo.entrypoints=websecure
      - traefik.http.routers.odoo.tls=true
      - traefik.http.routers.odoo.tls.certresolver=letsencrypt
      - traefik.http.services.odoo.loadbalancer.server.port=8069
      - traefik.docker.network=dokploy-network

networks:
  dokploy-network:
    external: true
  odoo-internal:
    driver: bridge
